### PR TITLE
Allow ecc to be built independently using its own CMakeLists.txt file

### PR DESCRIPTION
**Pull request by chewi**
This makes cross-compiling easier, and saves having to build once each for TFE and TSE.

I considered using CMake's import/export feature, but there's little point when you're only importing one binary target. Pointing the ECC variable at the ecc binary itself is simpler.

I copied the minimum CMake version of 2.8.7 from the parent project. To be confident this would actually work, I tested building under CentOS 7 with CMake 2.8.12.

### CODE REVIEW

**Comment by chewi** [comment]
I've realised this did break the Windows build, or at least Visual Studio 2022, due to it picking up the wrong `parser.h`, but as far as I can tell, it was already broken anyway. Despite what my profile might suggest, I don't care about the Windows build that much, but with yours being one of the more prominent forks, it would be a shame to leave it broken. I think I've nearly got it working, so I'll see what I can do.

**Comment by ptitSeb** [comment]
Ah yes, if the windows build can be fixed, that would be great. I haven't tried a windows build in ages, but I'll check how it works at some yes, it would be good.
(also, I'll to work on some CI at some point)

**Comment by chewi** [comment]
I've been making some progress but it's very slow. It's more broken than I thought. When did you last do a Windows build and was it with Visual Studio or MSVC? At least Visual Studio seems broken since Ryan's changes. For example, it looks for `#include "StdH.h"` in most source files to use the precompiled headers, but Ryan changed most of these to `#include "Engine/StdH.h"` or similar so it breaks. I can fix that, but it's just the tip of the iceberg. Or maybe you'd prefer to drop Visual Studio and just use CMake? There seem to be a lot of other MSVC-specific issues that would affect CMake too though. I briefly tried MinGW, but I don't think that ever worked.

**Comment by ptitSeb** [comment]
Can't remember, it was quite a long time ago.
I have some VS2019 installed...

**Comment by chewi** [comment]
Stange. Maybe earlier versions didn't care if the precompiled headers weren't used then. Oh well, I'll persevere for now.

**Pull request merged**
